package com.proyecto.Layout;

import com.proyecto.dao.AlumnoDAO;
import com.proyecto.dao.AulaDAO;
import com.proyecto.dao.CarreraDAO;
import com.proyecto.dao.CursoDAO;
import com.proyecto.dao.DocenteDAO;
import com.proyecto.model.Alumno;
import com.proyecto.model.Aula;
import com.proyecto.model.AulaAlumnos;
import com.proyecto.model.Carrera;
import com.proyecto.model.Curso;
import com.proyecto.model.Docente;
import com.proyecto.model.Evaluacion;
import com.proyecto.util.Tablas;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel
 */
public class MenuAdministrador extends javax.swing.JFrame {

    private static MenuAdministrador instancia;
    Tablas tabla = new Tablas();

    AlumnoDAO alumno = new AlumnoDAO();
    CarreraDAO carrera = new CarreraDAO();
    CursoDAO curso = new CursoDAO();
    DocenteDAO docente = new DocenteDAO();
    AulaDAO aula = new AulaDAO();

    DefaultListModel<Carrera> modeloListaCarreras = new DefaultListModel<>();
    DefaultListModel<Curso> modeloListaCursos = new DefaultListModel<>();

    DefaultListModel<Alumno> modeloListaAlumnos = new DefaultListModel<>();

    public MenuAdministrador() {
        initComponents();
        tabla.TablaCurso(tablacursos);
        tabla.TablaAlumno(tablaalumnos);
        tabla.TablaCarrera(tablacarreras);
        tabla.TablaDocente(tabladocentes);
        tabla.TablaAula(tablaaulas);

        lcarreras.setModel(modeloListaCarreras);
        listcursos.setModel(modeloListaCursos);

        cargarCarrerasEnCombo(cbcarrea);
        cargarCarrerasEnCombo(combocarrera);
        cargarCursosEnCombo(cbcursosd);

        instancia = this;
        lalumnosagregados.setModel(modeloListaAlumnos);
    }

    public static MenuAdministrador getInstancia() {
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Inicio = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Alumnos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tnombrealumno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaalumnos = new javax.swing.JTable();
        bbuscaralumno = new javax.swing.JButton();
        tbuscaralumno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        beliminar1 = new javax.swing.JButton();
        bmodificaralumno = new javax.swing.JButton();
        bguardaralumno = new javax.swing.JButton();
        tapellidosalumno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tdnialumno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tcorreoalumno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combocarrera = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacursos = new javax.swing.JTable();
        bbuscar = new javax.swing.JButton();
        tbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tcurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbcarrea = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ch1 = new javax.swing.JCheckBox();
        ch2 = new javax.swing.JCheckBox();
        ch3 = new javax.swing.JCheckBox();
        ch5 = new javax.swing.JCheckBox();
        ch6 = new javax.swing.JCheckBox();
        ch7 = new javax.swing.JCheckBox();
        ch4 = new javax.swing.JCheckBox();
        beliminar = new javax.swing.JButton();
        bmodificar = new javax.swing.JButton();
        bguardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lcarreras = new javax.swing.JList<>();
        blimpiar = new javax.swing.JButton();
        bagregar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        beliminard = new javax.swing.JButton();
        bmodificard = new javax.swing.JButton();
        tapellidosd = new javax.swing.JTextField();
        bguardard = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabladocentes = new javax.swing.JTable();
        tdnid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        bbuscard = new javax.swing.JButton();
        tcorreod = new javax.swing.JTextField();
        tbuscard = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbcursosd = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        tnombred = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listcursos = new javax.swing.JList<>();
        bagregard = new javax.swing.JButton();
        blimpiard = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        tcontraseñad = new javax.swing.JTextField();
        Escritorio = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaaulas = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tcodigoaula = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        taforo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lalumnosagregados = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablacarreras = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        tcarrerac = new javax.swing.JTextField();
        bcrearcarrera = new javax.swing.JButton();
        bmodificarcarrera = new javax.swing.JButton();
        beliminarcarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1108, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        Inicio.addTab("INICIO", jPanel2);

        jLabel6.setText("Nombre del alumno");

        jLabel7.setText("Apellidos del alumno");

        tablaalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaalumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaalumnosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaalumnos);

        bbuscaralumno.setText("BUSCAR");
        bbuscaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscaralumnoActionPerformed(evt);
            }
        });

        tbuscaralumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar ID"));
        tbuscaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbuscaralumnoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("GESTION DE ALUMNOS");

        beliminar1.setText("ELIMINAR");
        beliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminar1ActionPerformed(evt);
            }
        });

        bmodificaralumno.setText("MODIFICAR");
        bmodificaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificaralumnoActionPerformed(evt);
            }
        });

        bguardaralumno.setText("GUARDAR");
        bguardaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardaralumnoActionPerformed(evt);
            }
        });

        jLabel10.setText("DNI");

        jLabel11.setText("Correo electrónico");

        jLabel8.setText("Carrera");

        javax.swing.GroupLayout AlumnosLayout = new javax.swing.GroupLayout(Alumnos);
        Alumnos.setLayout(AlumnosLayout);
        AlumnosLayout.setHorizontalGroup(
            AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlumnosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AlumnosLayout.createSequentialGroup()
                        .addGroup(AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AlumnosLayout.createSequentialGroup()
                                .addComponent(bguardaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bmodificaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(beliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tdnialumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tcorreoalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(combocarrera, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tapellidosalumno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tnombrealumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlumnosLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbuscaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bbuscaralumno)))
                .addGap(14, 14, 14))
        );
        AlumnosLayout.setVerticalGroup(
            AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlumnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbuscaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(bbuscaralumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AlumnosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tnombrealumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tapellidosalumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tdnialumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcorreoalumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combocarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bguardaralumno)
                            .addComponent(beliminar1)
                            .addComponent(bmodificaralumno))))
                .addGap(59, 59, 59))
        );

        Inicio.addTab("ALUMNOS", Alumnos);

        tablacursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablacursos);

        bbuscar.setText("BUSCAR");

        tbuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar ID"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("GESTION DE CURSOS");

        jLabel2.setText("Nombre del curso");

        jLabel3.setText("Carrera Asociada");

        cbcarrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcarreaActionPerformed(evt);
            }
        });

        jLabel4.setText("Evaluaciones");

        ch1.setText("PC1");

        ch2.setText("PC2");

        ch3.setText("PC3");

        ch5.setText("TA1");

        ch6.setText("TA2");

        ch7.setText("Partipación en Clase");

        ch4.setText("Examen Final");

        beliminar.setText("ELIMINAR");

        bmodificar.setText("MODIFICAR");

        bguardar.setText("GUARDAR");
        bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lcarreras);

        blimpiar.setText("LIMPIAR");

        bagregar.setText("AGREGAR");
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(bguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(bmodificar)
                                    .addGap(29, 29, 29)
                                    .addComponent(beliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(ch1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ch2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ch3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ch4))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(ch5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ch6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ch7)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tcurso, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbcarrea, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 623, Short.MAX_VALUE)
                        .addComponent(tbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bbuscar)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(bbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbcarrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bagregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blimpiar))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ch1)
                            .addComponent(ch2)
                            .addComponent(ch3)
                            .addComponent(ch4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ch5)
                            .addComponent(ch6)
                            .addComponent(ch7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bguardar)
                            .addComponent(beliminar)
                            .addComponent(bmodificar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        Inicio.addTab("CURSOS", jPanel3);

        beliminard.setText("ELIMINAR");

        bmodificard.setText("MODIFICAR");

        bguardard.setText("GUARDAR");
        bguardard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardardActionPerformed(evt);
            }
        });

        jLabel12.setText("DNI");

        tabladocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabladocentes);

        jLabel13.setText("Correo electrónico");

        bbuscard.setText("BUSCAR");

        tbuscard.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar ID"));

        jLabel14.setText("Asignar cursos ");

        jLabel15.setText("Nombre del docentes");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("GESTION DE DOCENTES");

        jLabel17.setText("Apellidos del docentes");

        jScrollPane5.setViewportView(listcursos);

        bagregard.setText("Agregar");
        bagregard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregardActionPerformed(evt);
            }
        });

        blimpiard.setText("Limpiar");

        jLabel24.setText("Contraseña");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bguardard, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(bmodificard)
                                .addGap(29, 29, 29)
                                .addComponent(beliminard, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbcursosd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bagregard)
                                    .addComponent(blimpiard)))
                            .addComponent(jLabel24)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tcontraseñad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(tdnid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(tcorreod))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(85, 85, 85)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tapellidosd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tnombred, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                        .addComponent(tbuscard, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bbuscard)))
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbuscard, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(bbuscard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tnombred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tapellidosd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel18)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tdnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcorreod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcontraseñad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbcursosd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bagregard))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bguardard)
                                    .addComponent(beliminard)
                                    .addComponent(bmodificard)))
                            .addComponent(blimpiard))
                        .addGap(27, 27, 27))))
        );

        Inicio.addTab("DOCENTES", jPanel5);

        tablaaulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tablaaulas);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("GESTION DE AULAS");

        jLabel20.setText("Codigo de Aula");

        jLabel21.setText("Aforo ");

        jLabel22.setText("Alumnos");

        jScrollPane7.setViewportView(lalumnosagregados);

        jButton1.setText("Agregar Alumno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");

        jButton4.setText("Eliminar");

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap(918, Short.MAX_VALUE))
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcodigoaula, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EscritorioLayout.createSequentialGroup()
                                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(taforo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EscritorioLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6))))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel19)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcodigoaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(15, 15, 15)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Inicio.addTab("AULAS", Escritorio);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("GESTION DE CARRERAS");

        tablacarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablacarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacarrerasMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tablacarreras);

        jLabel23.setText("Nombre de carrera");

        bcrearcarrera.setText("Crear");
        bcrearcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcrearcarreraActionPerformed(evt);
            }
        });

        bmodificarcarrera.setText("Modificar");
        bmodificarcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarcarreraActionPerformed(evt);
            }
        });

        beliminarcarrera.setText("Eliminar");
        beliminarcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarcarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(bcrearcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(bmodificarcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(beliminarcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcarrerac, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tcarrerac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bcrearcarrera)
                            .addComponent(bmodificarcarrera)
                            .addComponent(beliminarcarrera))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        Inicio.addTab("CARRERAS", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicio)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicio)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Aula_Alumno aulaalumno = new Aula_Alumno();
        aulaalumno.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    private void bguardaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardaralumnoActionPerformed
        // TODO add your handling code here:
        String nombre = tnombrealumno.getText().trim();
        String apellido = tapellidosalumno.getText().trim();
        String dni = tdnialumno.getText().trim();
        String correo = tcorreoalumno.getText().trim();
        String carreraAlumno = combocarrera.getSelectedItem().toString();

        if (nombre.isEmpty() || apellido.isEmpty() || dni.isEmpty() || correo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar completos.");
            return;
        }

        Alumno crearalumno = new Alumno(0, nombre, apellido, dni, correo, carreraAlumno);
        if (alumno.guardarAlumno(crearalumno)) {
            JOptionPane.showMessageDialog(null, "Alumno guardado correctamente.");
            limpiarCamposAlumno();
            tabla.TablaAlumno(tablaalumnos);
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar alumno.");
        }
    }//GEN-LAST:event_bguardaralumnoActionPerformed

    // GUARDAR CARRERA
    private void bcrearcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcrearcarreraActionPerformed
        // TODO add your handling code here:
        String nombre = tcarrerac.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa el nombre de la carrera.");
            return;
        }

        Carrera nuevaCarrera = new Carrera(0, nombre);
        boolean guardado = carrera.guardarCarrera(nuevaCarrera);

        if (guardado) {
            tcarrerac.setText("");
            cargarCarrerasEnCombo(cbcarrea);
            cargarCarrerasEnCombo(combocarrera);
            tabla.TablaCarrera(tablacarreras);
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar la carrera.");
        }

    }//GEN-LAST:event_bcrearcarreraActionPerformed

    private void bmodificarcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarcarreraActionPerformed
        // TODO add your handling code here:
        int fila = tablacarreras.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Selecciona una carrera para modificar.");
            return;
        }

        String idStr = tablacarreras.getValueAt(fila, 0).toString();
        int id = Integer.parseInt(idStr);

        String nuevoNombre = tcarrerac.getText().trim();

        if (nuevoNombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa el nuevo nombre de la carrera.");
            return;
        }

        Carrera nuevacarrrera = new Carrera(id, nuevoNombre);
        if (carrera.modificarCarrera(nuevacarrrera)) {
            JOptionPane.showMessageDialog(null, "Carrera modificada correctamente.");
            tcarrerac.setText("");
            tabla.TablaCarrera(tablacarreras);
            cargarCarrerasEnCombo(cbcarrea);
            cargarCarrerasEnCombo(combocarrera);
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar la carrera.");
        }
    }//GEN-LAST:event_bmodificarcarreraActionPerformed

    private void tablacarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacarrerasMouseClicked
        // TODO add your handling code here:
        int fila = tablacarreras.getSelectedRow();
        if (fila >= 0) {
            String nombre = tablacarreras.getValueAt(fila, 1).toString();
            tcarrerac.setText(nombre);
        }
    }//GEN-LAST:event_tablacarrerasMouseClicked

    private void beliminarcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarcarreraActionPerformed
        // TODO add your handling code here:
        int fila = tablacarreras.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Selecciona una carrera para eliminar.");
            return;
        }
        int confirmacion = JOptionPane.showConfirmDialog(
                null,
                "¿Estás seguro de que deseas eliminar esta carrera?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );
        if (confirmacion == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tablacarreras.getValueAt(fila, 0).toString());
            if (carrera.eliminarCarrera(id)) {
                JOptionPane.showMessageDialog(null, "Carrera eliminada correctamente.");
                tabla.TablaCarrera(tablacarreras);
                cargarCarrerasEnCombo(cbcarrea);
                cargarCarrerasEnCombo(combocarrera);
                tcarrerac.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar la carrera.");
            }
        }
    }//GEN-LAST:event_beliminarcarreraActionPerformed

    private void tbuscaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbuscaralumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbuscaralumnoActionPerformed

    private void bmodificaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificaralumnoActionPerformed
        // TODO add your handling code here:
        int fila = tablaalumnos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Selecciona un alumno de la tabla.");
            return;
        }

        int id = Integer.parseInt(tablaalumnos.getValueAt(fila, 0).toString());
        String nombre = tnombrealumno.getText().trim();
        String apellido = tapellidosalumno.getText().trim();
        String dni = tdnialumno.getText().trim();
        String correo = tcorreoalumno.getText().trim();
        String carreracb = combocarrera.getSelectedItem().toString();

        if (nombre.isEmpty() || apellido.isEmpty() || dni.isEmpty() || correo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar completos.");
            return;
        }

        Alumno crearalumno = new Alumno(id, nombre, apellido, dni, correo, carreracb);
        if (alumno.modificarAlumno(crearalumno)) {
            JOptionPane.showMessageDialog(null, "Alumno modificado.");
            limpiarCamposAlumno();
            tabla.TablaAlumno(tablaalumnos);
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar.");
        }
    }//GEN-LAST:event_bmodificaralumnoActionPerformed

    private void beliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminar1ActionPerformed
        // TODO add your handling code here:
        int fila = tablaalumnos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "⚠️ Selecciona un alumno para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Eliminar alumno?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tablaalumnos.getValueAt(fila, 0).toString());
            if (alumno.eliminarAlumno(id)) {
                JOptionPane.showMessageDialog(null, "Alumno eliminado.");
                limpiarCamposAlumno();
                tabla.TablaAlumno(tablaalumnos);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar.");
            }
        }
    }//GEN-LAST:event_beliminar1ActionPerformed

    private void bbuscaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscaralumnoActionPerformed
        // TODO add your handling code here:
        String idStr = tbuscaralumno.getText().trim();
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa un ID para buscar.");
            return;
        }
        try {
            int id = Integer.parseInt(idStr);
            Alumno buscaralumno = alumno.buscarAlumnoPorId(id);

            if (buscaralumno != null) {
                tnombrealumno.setText(buscaralumno.getNombrealumno());
                tapellidosalumno.setText(buscaralumno.getApellidosalumno());
                tdnialumno.setText(buscaralumno.getDNI());
                tcorreoalumno.setText(buscaralumno.getCorreoalumno());
                combocarrera.setSelectedItem(buscaralumno.getCarrera());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró alumno.");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "ID inválido.");
        }
    }//GEN-LAST:event_bbuscaralumnoActionPerformed

    private void tablaalumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaalumnosMouseClicked
        // TODO add your handling code here:
        int fila = tablaalumnos.getSelectedRow();
        if (fila >= 0) {
            String nombre = tablaalumnos.getValueAt(fila, 1).toString();
            String apellidos = tablaalumnos.getValueAt(fila, 2).toString();
            String Dni = tablaalumnos.getValueAt(fila, 3).toString();
            String correo = tablaalumnos.getValueAt(fila, 4).toString();
            String carreraalumnos = tablaalumnos.getValueAt(fila, 5).toString();
            tnombrealumno.setText(nombre);
            tapellidosalumno.setText(apellidos);
            tdnialumno.setText(Dni);
            tcorreoalumno.setText(correo);
            combocarrera.setSelectedItem(carreraalumnos);
        }
    }//GEN-LAST:event_tablaalumnosMouseClicked

    private void bguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardarActionPerformed
        String nombrecurso = tcurso.getText().trim();
        if (nombrecurso.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el nombre del curso.");
            return;
        }

        if (modeloListaCarreras.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Agrega al menos una carrera.");
            return;
        }

        List<Carrera> carrerasAsociadas = new ArrayList<>();
        for (int i = 0; i < modeloListaCarreras.size(); i++) {
            carrerasAsociadas.add(modeloListaCarreras.getElementAt(i));
        }

        List<String> examenes = new ArrayList<>();
        for (JCheckBox cb : Arrays.asList(ch1, ch2, ch3, ch4, ch5, ch6, ch7)) {
            if (cb.isSelected()) {
                examenes.add(cb.getText());
            }
        }

        if (examenes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona al menos un examen.");
            return;
        }

        Evaluacion evaluacion = new Evaluacion(0, "Evaluaciones", examenes);
        List<Evaluacion> evaluaciones = Arrays.asList(evaluacion);

        Curso crearcurso = new Curso(0, nombrecurso, carrerasAsociadas, evaluaciones);

        if (curso.guardarCurso(crearcurso)) {
            JOptionPane.showMessageDialog(this, "Curso guardado correctamente.");
            tcurso.setText("");
            modeloListaCarreras.clear();
            Arrays.asList(ch1, ch2, ch3, ch4, ch5, ch6, ch7).forEach(cb -> cb.setSelected(false));
            tabla.TablaCurso(tablacursos);
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar curso.");
        }
    }//GEN-LAST:event_bguardarActionPerformed

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
        Carrera seleccionar = (Carrera) cbcarrea.getSelectedItem();
        if (seleccionar != null) {
            boolean yaAgregada = false;
            for (int i = 0; i < modeloListaCarreras.size(); i++) {
                if (modeloListaCarreras.getElementAt(i).getId() == seleccionar.getId()) {
                    yaAgregada = true;
                    break;
                }
            }
            if (!yaAgregada) {
                modeloListaCarreras.addElement(seleccionar);
            } else {
                JOptionPane.showMessageDialog(this, "La carrera ya fue agregada.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una carrera válida.");
        }

    }//GEN-LAST:event_bagregarActionPerformed

    private void cbcarreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcarreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcarreaActionPerformed

    private void bguardardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardardActionPerformed
        // TODO add your handling code here:
        String nombreprofesor = tnombred.getText().trim();
        String apellidosdocente = tapellidosd.getText().trim();
        String dnidocente = tdnid.getText().trim();
        String correodocente = tcorreod.getText().trim();
        String constraseñaporfesor = tcontraseñad.getText().trim();

        List<Curso> Cursoasociado = new ArrayList<>();
        for (int i = 0; i < modeloListaCursos.size(); i++) {
            Cursoasociado.add(modeloListaCursos.getElementAt(i));
        }

        List<Integer> cursosId = Cursoasociado.stream()
                .map(Curso::getId)
                .collect(Collectors.toList());

        Docente creardocente = new Docente(0, nombreprofesor, apellidosdocente, dnidocente, correodocente, constraseñaporfesor);

        if (docente.guardarDocente(creardocente, cursosId)) {
            JOptionPane.showMessageDialog(this, "Docente guardado correctamente.");
            tcurso.setText("");
            modeloListaCarreras.clear();
            Arrays.asList(ch1, ch2, ch3, ch4, ch5, ch6, ch7).forEach(cb -> cb.setSelected(false));
            tabla.TablaDocente(tabladocentes);
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar curso.");
        }
    }//GEN-LAST:event_bguardardActionPerformed

    private void bagregardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregardActionPerformed
        // TODO add your handling code here:
        Curso seleccionar = (Curso) cbcursosd.getSelectedItem();
        if (seleccionar != null) {
            boolean yaAgregada = false;
            for (int i = 0; i < modeloListaCursos.size(); i++) {
                if (modeloListaCursos.getElementAt(i).getId() == seleccionar.getId()) {
                    yaAgregada = true;
                    break;
                }
            }
            if (!yaAgregada) {
                modeloListaCursos.addElement(seleccionar);
            } else {
                JOptionPane.showMessageDialog(this, "El curso ya fue agregado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un curso válida.");
        }
    }//GEN-LAST:event_bagregardActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String codigo = tcodigoaula.getText();
        int aforo;

        try {
            aforo = Integer.parseInt(taforo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Aforo debe ser un número entero.");
            return;
        }

        DefaultListModel<Alumno> modelo = (DefaultListModel<Alumno>) lalumnosagregados.getModel();

        List<Alumno> alumnosSeleccionados = new ArrayList<>();
        for (int i = 0; i < modelo.size(); i++) {
            alumnosSeleccionados.add(modelo.getElementAt(i));
        }

        Aula crearaula = new Aula(0, codigo, aforo, alumnosSeleccionados);

        if (aula.guardarAula(crearaula)) {
            JOptionPane.showMessageDialog(null, "Aula registrada correctamente.");
            limpiarCamposAlumno();
            tabla.TablaAula(tablaaulas);
            
        } else {
            JOptionPane.showMessageDialog(null, "Error al registrar aula.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    public void cargarCarrerasEnCombo(JComboBox<Carrera> combo) {
        combo.removeAllItems();
        List<Carrera> carreras = carrera.listarCarreras();

        for (Carrera c : carreras) {
            combo.addItem(c);
        }
    }

    public void cargarCursosEnCombo(JComboBox<Curso> combo) {
        combo.removeAllItems();
        List<Curso> cursos = curso.listarCursos();

        for (Curso c : cursos) {
            combo.addItem(c);
        }
    }

    private void limpiarCamposAlumno() {
        tnombrealumno.setText("");
        tapellidosalumno.setText("");
        tdnialumno.setText("");
        tcorreoalumno.setText("");
        tbuscaralumno.setText("");
        combocarrera.setSelectedIndex(0);
    }


    public void agregarAlumnos(List<AulaAlumnos> aulaAlumnosList) {
        for (AulaAlumnos a : aulaAlumnosList) {
            // Convertir AulaAlumnos a Alumno
            Alumno alumno = new Alumno();
            alumno.setId(a.getId());
            alumno.setNombrealumno(a.getNombre());
            alumno.setApellidosalumno(a.getApellidos());

            // Evitar duplicados
            if (!modeloListaAlumnos.contains(alumno)) {
                modeloListaAlumnos.addElement(alumno);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alumnos;
    private javax.swing.JPanel Escritorio;
    private javax.swing.JTabbedPane Inicio;
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bagregard;
    private javax.swing.JButton bbuscar;
    private javax.swing.JButton bbuscaralumno;
    private javax.swing.JButton bbuscard;
    private javax.swing.JButton bcrearcarrera;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton beliminar1;
    private javax.swing.JButton beliminarcarrera;
    private javax.swing.JButton beliminard;
    private javax.swing.JButton bguardar;
    private javax.swing.JButton bguardaralumno;
    private javax.swing.JButton bguardard;
    private javax.swing.JButton blimpiar;
    private javax.swing.JButton blimpiard;
    private javax.swing.JButton bmodificar;
    private javax.swing.JButton bmodificaralumno;
    private javax.swing.JButton bmodificarcarrera;
    private javax.swing.JButton bmodificard;
    private javax.swing.JComboBox<Carrera> cbcarrea;
    private javax.swing.JComboBox<Curso> cbcursosd;
    private javax.swing.JCheckBox ch1;
    private javax.swing.JCheckBox ch2;
    private javax.swing.JCheckBox ch3;
    private javax.swing.JCheckBox ch4;
    private javax.swing.JCheckBox ch5;
    private javax.swing.JCheckBox ch6;
    private javax.swing.JCheckBox ch7;
    private javax.swing.JComboBox<Carrera> combocarrera;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JList<Alumno> lalumnosagregados;
    private javax.swing.JList<Carrera> lcarreras;
    private javax.swing.JList<Curso> listcursos;
    private javax.swing.JTable tablaalumnos;
    private javax.swing.JTable tablaaulas;
    private javax.swing.JTable tablacarreras;
    private javax.swing.JTable tablacursos;
    private javax.swing.JTable tabladocentes;
    private javax.swing.JTextField taforo;
    private javax.swing.JTextField tapellidosalumno;
    private javax.swing.JTextField tapellidosd;
    private javax.swing.JTextField tbuscar;
    private javax.swing.JTextField tbuscaralumno;
    private javax.swing.JTextField tbuscard;
    private javax.swing.JTextField tcarrerac;
    private javax.swing.JTextField tcodigoaula;
    private javax.swing.JTextField tcontraseñad;
    private javax.swing.JTextField tcorreoalumno;
    private javax.swing.JTextField tcorreod;
    private javax.swing.JTextField tcurso;
    private javax.swing.JTextField tdnialumno;
    private javax.swing.JTextField tdnid;
    private javax.swing.JTextField tnombrealumno;
    private javax.swing.JTextField tnombred;
    // End of variables declaration//GEN-END:variables
}
